### PR TITLE
Style Awards and Prizes page

### LINKED ISSUE #79: Style Awards and Prizes

### PR DESCRIPTION
**Pull request by joemull**
Closes #79.

awards-prizes

awards-prizes-lg

### CODE REVIEW

**Comment by joemull** [comment]
I've now added the new images with alt text as well as captions with attribution and licenses.

awards-prizes-lg-new-images

**Review by Astronaut-resting — APPROVED** [review]
For me, the angle on the jacket in mobile version is a bit jarring, especially in context of the angles of the icon, and if there were time I'd suggest experimenting by something round in front of that part of the image or something. However, I acknowledge that this is a Carly design and therefore happy to just trust and approve if everyone else is.

**Comment by joemull** [comment]
How about this @Astronaut-resting ?

image

**Review by Astronaut-resting — APPROVED** [review]
Yes! This looks so much better and more balanced

**Pull request merged**
