### PR TITLE
Style journals

### LINKED ISSUE #40: Style Journals

### PR DESCRIPTION
**Pull request by joemull**
Closes #40.

- The ballet dancer's pony tail and foot aren't shown fully in this version unfortunately, but I will replace this image with an uncropped one at a later date
- Carly suggests adding a lead in the orange box like the other pages. Do we want to write something for this spot?
- The filter box narrows down the journals displayed as you type, based on matches with title, description, or keywords

journals

journals-lg

### CODE REVIEW

**Review by Astronaut-resting — APPROVED** [review]
All looks great. 
I think it would be helpful to have some intro text. I will look into that.

**Comment by Astronaut-resting** [comment]
How about this for text? 

**The OLH publishes open access journals covering a broad range of topics across the humanities, commanding the respect of the academic communities we serve.** 

With our flagship _Open Library of Humanities Journal_ featured, our journals are then arranged alphabetically by title. Journals can also be filtered by keyword and subject. All our scholarship is published under CC-BY international licence to help ensure the widest possible readership.

**Comment by Astronaut-resting** [comment]
Urgh, I guess we could just cut that sentence, then? Unless you have another suggestion? I think it is okay to cut if need be.

**Comment by joemull** [comment]
> All looks great. Only thing I would say is that users said that they didn't immediately pick up that OLHJ was the flagship journal and not knowing this prevented them from understanding that they were organised in alphabetical order. We have since changed the explainer text, but I wonder if there is a visual way to represent that it is different from the others, while still keeping within the guidelines? I think it would be helpful to have some intro text. I will look into that.

@Astronaut-resting OK, I think we can highlight it visually if we want at a later date. Will add a note to ask editorial about that.

I will also add the copy you suggest, maybe modifying the copyright line a bit: "most of our journals are CC-BY"?

> the filter box will be quite far away from the list of journals on mobile, might this confuse folks?

@ajrbyers thanks for picking up on that. I had thought about that too. I opted to have the orange lead box drop away when someone types something, so the journals are closer to the input, like this:

[Screencast from 2023-08-24 09-59-46.webm](https://github.com/BirkbeckCTP/hourglass/assets/47217308/171530cf-d10f-4ae9-a5c4-17ddf6bb23da)

Do you think that does enough, or would the page design have to be more compact overall for a filter feature to be usable?

**Comment by ajrbyers** [comment]
> >

I think that works quite well, Joe!

**Comment by joemull** [comment]
@Astronaut-resting you can check the updated copy by clicking on the relevant "commit" above, so in this case the one that reads "Load journals from view to get proper sequence; update copy".

**Comment by Astronaut-resting** [comment]
@joemull update from yesterday's meeting with Caroline. Copy should be the following: 

**The OLH publishes open access journals covering a broad range of topics across the humanities, commanding the respect of the academic communities we serve.**  
 
Our journals are arranged alphabetically by title. Journals can also be filtered by keyword and subject. The default for articles is the CC-BY international licence to help ensure the widest possible readership.  

Decision on positioning of _OLHJ_: Just have it in alphabetical order. No need to set it apart in any way. It might do more harm than good because of the risks associated with vanity publishing and prestige etc.

**Pull request merged**
