### PR TITLE
Updates to accessibility page and other minor edits

### PR DESCRIPTION
**Pull request by joemull**
Here is the main change:

image

### CODE REVIEW

**Review by StephDriver — CHANGES_REQUESTED** [review]
Only the hourglass changes are in the milestone - we need some reference to Janeway changes I think.  If we put about this being part of the larger Janeway Accessibility Project, and then that changes identified as part of Janeway rather than hourglass will be implemented through that.

**Review by StephDriver — APPROVED** [review]
looks fine to me

**Comment by joemull** [comment]
This change should kind of go up ASAP so how about I switch the second reviewer to Siobhan, since Katherine is in Minnesota?

**Review by S-Haime — APPROVED** [review]
Looks good to me, no further comments.

**Pull request merged**
