### PR TITLE
Publisher Policies

### LINKED ISSUE #157: Style Publisher Policies
- [x] Use openlibhums version of policies, which is newer
- [x] Use vases and blue circle as artwork

### PR DESCRIPTION
**Pull request by joemull**
Closes #157.

publisher-policies

publisher-policies-lg

### CODE REVIEW

**Comment by Astronaut-resting** [comment]
I'm wondering about this page, whether it would be better _not_ to have it alternating right and left but to just have it as a more traditional document, quite similar to how we have it on the [site](https://www.openlibhums.org/site/publisher-policies/) now. My reasons for this are: 

1) This is a different genre of writing to the rest of the site. More formal and "strong arm of the law". So the playful alignment seems less appropriate in this context. 
2)Anything that we can do to break up the left/right alignment now and then is good I think. It is cool but if we do it all the time it becomes very same-y. 

This is my sense of it -- but would be interested to hear what @severett89 has to say. It is very much your baby, so happy to go with your sense of what's best. 

Other small things: 

In the desktop version, I wonder if you could pull the pots in a bit so make it a little neater -- see screenshot. Is it possible to also pull the blue dot out to the left (like in the mobile version) to make it a bit less cramped? No worries if this is too much of a bother. 

Screenshot 2023-10-20 at 14 06 45

**Comment by severett89** [comment]
I agree with Katherine on this in terms of staggering the sections throughout. I think what is odd to me is how 'Rigorous Peer Review' suddenly jumps out to the left when the other policy info in that section is to the right. When the main section changes (blue boxes) I think it make a nice shift to have the following sections left justified.

What happens if we were to just have all the white box sections as one white box, then splits off with the blue header, and then continues the ethics and malpractice statement as one white box? This might make the page a bit flat though so might be worth seeing how it looks first?

**Comment by Astronaut-resting** [comment]
I think flat is good sometimes. Some things aren’t fun. Some things are SERIOUS.

Best wishes,
Katherine

Dr Katherine Parker-Hay
Editorial Officer, Open Library of Humanities<https://www.openlibhums.org/>
Department of English, Theatre and Creative Writing
School of Arts, Birkbeck, University of London


From: Simon Everett ***@***.***>
Date: Friday, 20 October 2023 at 14:24
To: BirkbeckCTP/hourglass ***@***.***>
Cc: Katherine Parker-Hay (Staff) ***@***.***>, Review requested ***@***.***>
Subject: Re: [BirkbeckCTP/hourglass] Publisher Policies (PR #158)

I agree with Katherine on this in terms of staggering the sections throughout. I think what is odd to me is how 'Rigorous Peer Review' suddenly jumps out to the left when the other policy info in that section is to the right. When the main section changes (blue boxes) I think it make a nice shift to have the following sections left justified.

What happens if we were to just have all the white box sections as one white box, then splits off with the blue header, and then continues the ethics and malpractice statement as one white box? This might make the page a bit flat though so might be worth seeing how it looks first?

**Comment by severett89** [comment]
Policies can be fun…

I find them fun. Actually not really ‘fun’, just it irritates me when things aren’t codified. So they give me satisfaction? That’s more precise I think.

S


Dr Simon Everett
Editorial Officer, Open Library of Humanities<https://www.openlibhums.org/>
Birkbeck, University of London
Managing Editor, Open Library of Humanities Journal<https://olh.openlibhums.org/>

Support us to create an open-access, not-for-profit future for academic publishing<https://www.openlibhums.org/plugins/supporters/>.

Explore our open-source, in-house developed publishing platform Janeway<https://janeway.systems/>.

From: Katherine Parker-Hay ***@***.***>
Date: Friday, 20 October 2023 at 14:52
To: BirkbeckCTP/hourglass ***@***.***>
Cc: Simon Everett OLH ***@***.***>, Mention ***@***.***>
Subject: Re: [BirkbeckCTP/hourglass] Publisher Policies (PR #158)
I think flat is good sometimes. Some things aren’t fun. Some things are SERIOUS.

Best wishes,
Katherine

Dr Katherine Parker-Hay
Editorial Officer, Open Library of Humanities<https://www.openlibhums.org/><https://linkprotect.cudasvc.com/url?a=https%3a%2f%2fwww.openlibhums.org%2f%26gt%3b&c=E,1,ZIKyh-7-c6oa0YD8RdBAGI45gMMcBsUACyLaKdqEIy6uSmOJRxmfBdQe7TC2SlW2gbA7ZmAoLwe5xfMsYTTA0-Mw5P6G1nRQiH6_YA-JLWw,&typo=1&ancr_add=1>
Department of English, Theatre and Creative Writing
School of Arts, Birkbeck, University of London


From: Simon Everett ***@***.***>
Date: Friday, 20 October 2023 at 14:24
To: BirkbeckCTP/hourglass ***@***.***>
Cc: Katherine Parker-Hay (Staff) ***@***.***>, Review requested ***@***.***>
Subject: Re: [BirkbeckCTP/hourglass] Publisher Policies (PR #158)

I agree with Katherine on this in terms of staggering the sections throughout. I think what is odd to me is how 'Rigorous Peer Review' suddenly jumps out to the left when the other policy info in that section is to the right. When the main section changes (blue boxes) I think it make a nice shift to have the following sections left justified.

What happens if we were to just have all the white box sections as one white box, then splits off with the blue header, and then continues the ethics and malpractice statement as one white box? This might make the page a bit flat though so might be worth seeing how it looks first?

**Comment by joemull** [comment]
Just to note, with the latest commit, I've combined the white boxes under each main section, and I've adjusted the position of the blue circle.

**Pull request merged**
